precompile(Tuple{typeof(JuliaInterpreter.__init__)})
precompile(Tuple{typeof(Revise.__init__)})
precompile(Tuple{typeof(Revise.watch_package_callback), Base.PkgId})
precompile(Tuple{Revise.TaskThunk})
precompile(Tuple{typeof(Revise.watch_manifest), String})
precompile(Tuple{Revise.var"#107#108"})
precompile(Tuple{typeof(REPL.LineEdit.activate), REPL.LineEdit.TextInterface, REPL.LineEdit.MIState, REPL.Terminals.AbstractTerminal, REPL.Terminals.TextTerminal})
precompile(Tuple{typeof(REPL.LineEdit.refresh_multi_line), REPL.Terminals.UnixTerminal, Any})
precompile(Tuple{typeof(Revise.revise_first), Expr})
precompile(Tuple{typeof(Base.isempty), Base.Set{Tuple{Revise.PkgData, String}}})
precompile(Tuple{typeof(Revise.watch_package), Base.PkgId})
precompile(Tuple{typeof(Revise.iswritable), String})
precompile(Tuple{typeof(ColorTypes.__init__)})
precompile(Tuple{typeof(DocStringExtensions.__init__)})
precompile(Tuple{typeof(OpenLibm_jll.__init__)})
precompile(Tuple{typeof(CompilerSupportLibraries_jll.__init__)})
precompile(Tuple{typeof(OpenSpecFun_jll.__init__)})
precompile(Tuple{typeof(OpenSpecFun_jll.find_artifact_dir)})
precompile(Tuple{typeof(Base.invokelatest), Any})
precompile(Tuple{typeof(JLLWrappers.get_julia_libpaths)})
precompile(Tuple{typeof(ColorVectorSpace.__init__)})
precompile(Tuple{typeof(Revise.watch_package), Base.PkgId})
precompile(Tuple{typeof(Requires.__init__)})
precompile(Tuple{typeof(Requires.loadpkg), Base.PkgId})
precompile(Tuple{typeof(fzf_jll.__init__)})
precompile(Tuple{typeof(fzf_jll.find_artifact_dir)})
precompile(Tuple{typeof(Parsers.__init__)})
precompile(Tuple{typeof(Base.resize!), Array{Base.GMP.BigInt, 1}, Int64})
precompile(Tuple{typeof(Base.resize!), Array{Base.MPFR.BigFloat, 1}, Int64})
precompile(Tuple{typeof(Bzip2_jll.__init__)})
precompile(Tuple{typeof(Bzip2_jll.find_artifact_dir)})
precompile(Tuple{typeof(Zlib_jll.__init__)})
precompile(Tuple{typeof(FreeType2_jll.__init__)})
precompile(Tuple{typeof(FreeType2_jll.find_artifact_dir)})
precompile(Tuple{typeof(FriBidi_jll.__init__)})
precompile(Tuple{typeof(FriBidi_jll.find_artifact_dir)})
precompile(Tuple{typeof(Libiconv_jll.__init__)})
precompile(Tuple{typeof(Libiconv_jll.find_artifact_dir)})
precompile(Tuple{typeof(Libffi_jll.__init__)})
precompile(Tuple{typeof(Libffi_jll.find_artifact_dir)})
precompile(Tuple{typeof(XML2_jll.__init__)})
precompile(Tuple{typeof(XML2_jll.find_artifact_dir)})
precompile(Tuple{typeof(Gettext_jll.__init__)})
precompile(Tuple{typeof(Gettext_jll.find_artifact_dir)})
precompile(Tuple{typeof(PCRE2_jll.__init__)})
precompile(Tuple{typeof(Libmount_jll.__init__)})
precompile(Tuple{typeof(Libmount_jll.find_artifact_dir)})
precompile(Tuple{typeof(Glib_jll.__init__)})
precompile(Tuple{typeof(Glib_jll.find_artifact_dir)})
precompile(Tuple{typeof(Pixman_jll.__init__)})
precompile(Tuple{typeof(Pixman_jll.find_artifact_dir)})
precompile(Tuple{typeof(libpng_jll.__init__)})
precompile(Tuple{typeof(libpng_jll.find_artifact_dir)})
precompile(Tuple{typeof(Libuuid_jll.__init__)})
precompile(Tuple{typeof(Libuuid_jll.find_artifact_dir)})
precompile(Tuple{typeof(Expat_jll.__init__)})
precompile(Tuple{typeof(Expat_jll.find_artifact_dir)})
precompile(Tuple{typeof(Fontconfig_jll.__init__)})
precompile(Tuple{typeof(Fontconfig_jll.find_artifact_dir)})
precompile(Tuple{typeof(Base.getindex), Base.EnvDict, String})
precompile(Tuple{typeof(Libgpg_error_jll.__init__)})
precompile(Tuple{typeof(Libgpg_error_jll.find_artifact_dir)})
precompile(Tuple{typeof(Libgcrypt_jll.__init__)})
precompile(Tuple{typeof(Libgcrypt_jll.find_artifact_dir)})
precompile(Tuple{typeof(XSLT_jll.__init__)})
precompile(Tuple{typeof(XSLT_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_libXau_jll.__init__)})
precompile(Tuple{typeof(Xorg_libXau_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_libXdmcp_jll.__init__)})
precompile(Tuple{typeof(Xorg_libXdmcp_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_libpthread_stubs_jll.__init__)})
precompile(Tuple{typeof(Xorg_libpthread_stubs_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_libxcb_jll.__init__)})
precompile(Tuple{typeof(Xorg_libxcb_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_xtrans_jll.__init__)})
precompile(Tuple{typeof(Xorg_xtrans_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_libX11_jll.__init__)})
precompile(Tuple{typeof(Xorg_libX11_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_libXext_jll.__init__)})
precompile(Tuple{typeof(Xorg_libXext_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_libXrender_jll.__init__)})
precompile(Tuple{typeof(Xorg_libXrender_jll.find_artifact_dir)})
precompile(Tuple{typeof(LZO_jll.__init__)})
precompile(Tuple{typeof(LZO_jll.find_artifact_dir)})
precompile(Tuple{typeof(Cairo_jll.__init__)})
precompile(Tuple{typeof(Cairo_jll.find_artifact_dir)})
precompile(Tuple{typeof(Graphite2_jll.__init__)})
precompile(Tuple{typeof(Graphite2_jll.find_artifact_dir)})
precompile(Tuple{typeof(HarfBuzz_jll.__init__)})
precompile(Tuple{typeof(HarfBuzz_jll.find_artifact_dir)})
precompile(Tuple{typeof(libass_jll.__init__)})
precompile(Tuple{typeof(libass_jll.find_artifact_dir)})
precompile(Tuple{typeof(libfdk_aac_jll.__init__)})
precompile(Tuple{typeof(libfdk_aac_jll.find_artifact_dir)})
precompile(Tuple{typeof(LAME_jll.__init__)})
precompile(Tuple{typeof(LAME_jll.find_artifact_dir)})
precompile(Tuple{typeof(Ogg_jll.__init__)})
precompile(Tuple{typeof(Ogg_jll.find_artifact_dir)})
precompile(Tuple{typeof(libvorbis_jll.__init__)})
precompile(Tuple{typeof(libvorbis_jll.find_artifact_dir)})
precompile(Tuple{typeof(libaom_jll.__init__)})
precompile(Tuple{typeof(libaom_jll.find_artifact_dir)})
precompile(Tuple{typeof(x264_jll.__init__)})
precompile(Tuple{typeof(x264_jll.find_artifact_dir)})
precompile(Tuple{typeof(x265_jll.__init__)})
precompile(Tuple{typeof(x265_jll.find_artifact_dir)})
precompile(Tuple{typeof(OpenSSL_jll.__init__)})
precompile(Tuple{typeof(OpenSSL_jll.find_artifact_dir)})
precompile(Tuple{typeof(Opus_jll.__init__)})
precompile(Tuple{typeof(Opus_jll.find_artifact_dir)})
precompile(Tuple{typeof(FFMPEG_jll.__init__)})
precompile(Tuple{typeof(FFMPEG_jll.find_artifact_dir)})
precompile(Tuple{typeof(Libglvnd_jll.__init__)})
precompile(Tuple{typeof(Libglvnd_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_libXfixes_jll.__init__)})
precompile(Tuple{typeof(Xorg_libXfixes_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_libXcursor_jll.__init__)})
precompile(Tuple{typeof(Xorg_libXcursor_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_libXi_jll.__init__)})
precompile(Tuple{typeof(Xorg_libXi_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_libXinerama_jll.__init__)})
precompile(Tuple{typeof(Xorg_libXinerama_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_libXrandr_jll.__init__)})
precompile(Tuple{typeof(Xorg_libXrandr_jll.find_artifact_dir)})
precompile(Tuple{typeof(GLFW_jll.__init__)})
precompile(Tuple{typeof(GLFW_jll.find_artifact_dir)})
precompile(Tuple{typeof(JpegTurbo_jll.__init__)})
precompile(Tuple{typeof(JpegTurbo_jll.find_artifact_dir)})
precompile(Tuple{typeof(LERC_jll.__init__)})
precompile(Tuple{typeof(LERC_jll.find_artifact_dir)})
precompile(Tuple{typeof(Zstd_jll.__init__)})
precompile(Tuple{typeof(Zstd_jll.find_artifact_dir)})
precompile(Tuple{typeof(Libtiff_jll.__init__)})
precompile(Tuple{typeof(Libtiff_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_xcb_util_jll.__init__)})
precompile(Tuple{typeof(Xorg_xcb_util_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_xcb_util_wm_jll.__init__)})
precompile(Tuple{typeof(Xorg_xcb_util_wm_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_xcb_util_image_jll.__init__)})
precompile(Tuple{typeof(Xorg_xcb_util_image_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_xcb_util_keysyms_jll.__init__)})
precompile(Tuple{typeof(Xorg_xcb_util_keysyms_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_xcb_util_renderutil_jll.__init__)})
precompile(Tuple{typeof(Xorg_xcb_util_renderutil_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_libxkbfile_jll.__init__)})
precompile(Tuple{typeof(Xorg_libxkbfile_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_xkbcomp_jll.__init__)})
precompile(Tuple{typeof(Xorg_xkbcomp_jll.find_artifact_dir)})
precompile(Tuple{typeof(Xorg_xkeyboard_config_jll.__init__)})
precompile(Tuple{typeof(Xorg_xkeyboard_config_jll.find_artifact_dir)})
precompile(Tuple{typeof(Wayland_jll.__init__)})
precompile(Tuple{typeof(Wayland_jll.find_artifact_dir)})
precompile(Tuple{typeof(Wayland_protocols_jll.__init__)})
precompile(Tuple{typeof(Wayland_protocols_jll.find_artifact_dir)})
precompile(Tuple{typeof(xkbcommon_jll.__init__)})
precompile(Tuple{typeof(xkbcommon_jll.find_artifact_dir)})
precompile(Tuple{typeof(Qt5Base_jll.__init__)})
precompile(Tuple{typeof(Qt5Base_jll.find_artifact_dir)})
precompile(Tuple{typeof(GR_jll.__init__)})
precompile(Tuple{typeof(GR_jll.find_artifact_dir)})
precompile(Tuple{typeof(GR.GRPreferences.__init__)})
precompile(Tuple{typeof(Preferences.load_preference), Base.UUID, String, String})
precompile(Tuple{typeof(Base.setindex!), Base.RefValue{Union{Nothing, String}}, String})
precompile(Tuple{typeof(Plots.__init__)})
precompile(Tuple{typeof(Base.pop!), Base.Dict{Symbol, Any}, Symbol, Symbol})
precompile(Tuple{typeof(Base.getindex), Base.Dict{Symbol, PlotThemes.PlotTheme}, Symbol})
precompile(Tuple{typeof(Base.haskey), NamedTuple{(:categorical,), Tuple{Nothing}}, Symbol})
precompile(Tuple{typeof(Base.map), typeof(Base.Broadcast.broadcastable), Tuple{Int64}})
precompile(Tuple{typeof(Base.Broadcast._getindex), Tuple{Int64, Int64}, Int64})
precompile(Tuple{typeof(Base.promote_type), Type, Type, Type})
precompile(Tuple{typeof(PlotUtils.cgrad), ColorSchemes.ColorScheme{Array{ColorTypes.RGB{Float64}, 1}, String, String}})
precompile(Tuple{typeof(Plots.treats_y_as_x), Symbol})
precompile(Tuple{Base.var"##parse#477", Nothing, typeof(Base.parse), Type{Bool}, String})
precompile(Tuple{typeof(Requires.isprecompiling)})
precompile(Tuple{typeof(Requires.listenpkg), Any, Base.PkgId})
precompile(Tuple{typeof(Requires.loaded), Base.PkgId})
precompile(Tuple{typeof(Requires.callbacks), Base.PkgId})
precompile(Tuple{typeof(Revise.revise_dir_queued), String})
precompile(Tuple{typeof(REPL.LineEdit.refresh_multi_line), REPL.Terminals.TerminalBuffer, REPL.LineEdit.ModeState})
precompile(Tuple{REPL.LineEdit.var"#25#26"{REPL.LineEdit.var"#117#171", String}, Any, Any})
precompile(Tuple{REPL.LineEdit.var"#117#171", REPL.LineEdit.MIState, Any, Vararg{Any}})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Nothing, Int64}, Int64})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Nothing, Int64}, Int64, Int64})
precompile(Tuple{REPL.var"#48#53"{REPL.REPLBackendRef}})
precompile(Tuple{typeof(FileWatching.uvfinalize), FileWatching.FileMonitor})
